# Generated by Django 4.1 on 2022-09-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAccion', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLab', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefonoLab', models.IntegerField()),
            ],
        ),
    ]
