# Generated by Django 4.1 on 2022-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_accion_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSucursal', models.CharField(max_length=40)),
                ('direccionSucursal', models.CharField(max_length=50)),
                ('municipioSucursal', models.CharField(max_length=30)),
                ('ciudadSucursal', models.CharField(max_length=30)),
                ('telefonoSucursal', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='accion',
            old_name='descripcion',
            new_name='descripcionAccion',
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='direccion',
            new_name='direccionLab',
        ),
    ]
